name: Despliegue Automatico Yonimon

on:
  push:
    branches:
      - main  # Si tu rama principal se llama master, cambia "main" por "master"

jobs:
  deploy:
    name: Subiendo cambios al servidor de forma segura
    runs-on: ubuntu-latest
    steps:
    - name: Clonar codigo
      uses: actions/checkout@v3

    - name: Enviar a InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /htdocs/
